name: Build & Run

on:
  push:
    branches:
      - master
      - ci
  pull_request:

jobs:
  linux:
    name: g++ -std=c++${{matrix.std}}
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        std: [ 17, 20 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: >
          cmake -S . -B build
          -DCMAKE_C_COMPILER=gcc-11
          -DCMAKE_CXX_COMPILER=g++-11
          -DCMAKE_CXX_STANDARD=${{matrix.std}}

      - name: Build
        run: cmake --build build

      - name: Run
        run: ctest --extra-verbose --test-dir build

  macos:
    name: clang++ -std=c++${{matrix.std}}
    runs-on: macos-12

    strategy:
      fail-fast: true
      matrix:
        std: [ 17, 20 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: >
          cmake -S . -B build
          -DCMAKE_CXX_STANDARD=${{matrix.std}}

      - name: Build
        run: cmake --build build

      - name: Run
        run: ctest --extra-verbose --test-dir build

  windows:
    name: cl /std:c++${{matrix.std}}
    runs-on: windows-2022

    strategy:
      fail-fast: true
      matrix:
        std: [ 17, 20 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure
        run: >
          cmake -S . -B build
          -DCMAKE_CXX_STANDARD=${{matrix.std}}

      - name: Build
        run: cmake --build build --config Debug

      - name: Run
        run: ctest --extra-verbose --test-dir build --build-config Debug
